name: Pipeline

on:
  push:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main1' }}
    steps:
      - name: Build
        run: |
          echo "Building....."
      
  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.run_attempt > 3 }}
    steps:
      - name: This step only runs if the push is to main
        run: echo "This job runs only on pushes to main branch."
        
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    if: ${{ github.run_attempt <= 2 }}

    steps:
      - name: one
        if: ${{ github.run_attempt > 4 }}
        run: |
          echo "deploying....."   
      - name: two
        if: ${{ github.run_attempt == 10 }}
        run: |
          echo "deploying....."        
      
      - name: three
        if: ${{ github.run_attempt <= 2 }}
        run: |
          echo "deploying..... "   
          exit 1    
